# Generated by Django 2.1.4 on 2018-12-31 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_socialnetwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='facebook',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='github',
            field=models.URLField(blank=True, default=''),
        ),
    ]
