# Generated by Django 2.1 on 2018-12-31 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20181231_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialnetwork',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='github',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='socialnetwork',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
