# Generated by Django 2.1.4 on 2019-01-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20190106_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='lugar',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='nombre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
