# Generated by Django 2.1.4 on 2019-01-07 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_auto_20190106_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='id',
        ),
        migrations.AlterField(
            model_name='evento',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
