# Generated by Django 2.1.4 on 2019-01-07 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0010_lugares'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='user',
        ),
        migrations.RemoveField(
            model_name='lugares',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
        migrations.DeleteModel(
            name='Lugares',
        ),
    ]
